version: '2'
services:
    db:
        image: mysql:5.7
        volumes:
            - "./../.data/db:/var/lib/mysql"
        restart: always
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: just
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
    web:
        volumes:
            - "./:/var/www/html"
        container_name: post-api
        depends_on:
            - db
        image: alanfreire/post-api
        external_links:
            - db:db
        ports:
            - "80:80"
        restart: always